### ISSUE TITLE
New docs on how to write adaptors

### ISSUE THREAD

**Issue by lakhassane** [OpenFn/docs#122]

**Comment by taylordowns2000** [comment]
Leaving this open, @lakhassane , because I want more. We've had such great conversations recently about error handling, how we name adaptor operations, how those adaptors use `language-common.http`, etc.

Can you add a few more sentences with technical considerations and _advice_ for people writing new adaptors ([here](https://docs.openfn.org/documentation/build/adaptors#developing-a-new-adaptor)) or new operations ([here](https://docs.openfn.org/documentation/build/adaptors#extending-an-adaptor))?

Finally, there's no mention of `make` or `npm run test`... I'd hope that our guidance included best practices on how to build and test new operations and adaptors.
