### ISSUE TITLE
One free job available for mapping to sandbox

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/docs#15]
It would be helpful to have at least one job reserved for testing new forms, or new functionality involving existing forms in a sandbox, while leaving all existing forms actively mapped to production.

**Comment by taylordowns2000** [comment]
@Natalieflp , while this would be difficult to achieve per se, we are currently building a `test adaptor` that will spit out the exact `destination payload` for a given `job` and `receipt`. This way, you'll be able to instantly test `jobs` to see that you've written them correctly.

Down the line, it's possible that we could allow `jobs` to run when the `credential URL` is `https://test.salesforce.com`, even if a user was over their limit, but I can't commit to that now. (I think that is specifically what you were hoping for.)

Hope this is a helpful start. I will keep you posted on the progress of the `test adaptor`.

Taylor

**Comment by taylordowns2000** [comment]
@Natalieflp , in conversation with @aleksagk it seems like we should allow users to "manually process" a single `receipt` per Job, regardless of whether or not that job is set to `autoprocess`.

This would allow you to set up the new job, linked to a sandbox or a production account, and test that job (pressing retry as many times as you'd like, for a single receipt) before deactivating the old job and activating the new.

**Comment by Natalieflp** [comment]
So every new job would be able to link to either a sandbox or production? Even while all other jobs, for example, were linked to production?

**Comment by taylordowns2000** [comment]
Yes! Since the distinction between "sandbox" and "production" is just a
Salesforce thing, OpenFn doesn't (and can't) have an opinion about it. Jobs
can make use of whichever adaptor and credential they want. We restrict the
number of jobs which can be set to `autoprocess` and we will limit the
number of receipts that can be processed and submitted for a job which is
not set to `autoprocess`. This seems to be the fairest way to allow users
to test out jobs (no matter what kind of DHIS2, OpenMRS, or Salesforce
system they're linked to) before "switching them on."

Taylor

**Comment by taylordowns2000** [comment]
@Natalieflp , I'll soon be working on offline testing tools which will cut down the amount of runs required to get a job set up correctly. Using `fn-lang` it's possible to test a job `expression` against a `state` with data, a config, etc. from your local machine. Going to mark this closed, as making these devtools easier to use is taking precedence.
