### ISSUE TITLE
Edit Receipt view: display ODK field labels in addition to field names

### ISSUE THREAD

**Issue by aleksagk** [OpenFn/docs#24]
Would be helpful to display the ODK field label alongside the ODK field name (or perhaps have the option to view the label if you hover over the name - like the Salesforce help text option). This will help the system admin better understand how to update the field values if there's an error in the submission. In ODK, the field labels can sometimes be long questions that are hard to summarize into short field names.

**Comment by taylordowns2000** [comment]
@aleksagk , in the short-term this doesn't seem plausible—that edit payload screen is built to give the user a chance to modify _whatever_ JSON has arrived from _wherever_, and since ODK doesn't send field labels in the JSON message body, implementing something like this would mean building an ODK adaptor to then download X-forms and match them to the payload at hand whenever this page was visited.

I'm going to close this issue for now, as it feels like the platform's new direction doesn't quite allow for it.
