### ISSUE TITLE
Add documentation on how to pass state from 1 job to another when working locally vs on platform

### ISSUE THREAD

**Issue by daissatou2** [OpenFn/docs#339]
The OS4H team expressed confusion on how to pass state from one job to another when working locally during one of thier homework exercises. Please add documentation to docs.openfn.org which explains how to do this and how this is different from working on the platform. Consider creating a new docs page in the Build -> Jobs section, or expanding on this existing [page](https://docs.openfn.org/documentation/jobs/state) which discusses `state`.

**Comment by josephjclark** [comment]
So the new runtime needs to be able to accept an Execution Plan as an input (see https://github.com/OpenFn/kit/issues/202). At its simplest this is just an array of jobs, at its more complex its a full workflow graph.

The CLI would then support this (almost) for free if you pass a path to `execution-plan.json` rather than `job.js`.

In the meantime, yes the expected approach is to run each job one at a time, passing in the correct state and credentials (which I can see is not a nice process).
