### ISSUE TITLE
Reprocessing Errors

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/docs#52]
Functionality that would be very helpful in reprocessing errors when there are many:

- [ ] 1) Mass reprocessing (for example, the ability to select more than one receipt and click a mass reprocess button).
- [x] 2) Display of the error code on the activity main page OR, be able to filter by error code. 
- [x] 3) Be able to page through receipts without returning to activity page (for example, there would be arrow keys on each receipt page that would say previous receipt, next receipt), so once an error is resolved you can move on to the next error submission.

**Comment by aleksagk** [comment]
@taylordowns2000 Putting on your radar that this is pretty important for our team among the list of items in the backlog when it comes to troubleshooting. Currently it's easy to miss out on errors and therefore fail to sync some submissions, leading to missing data in client systems. cc @Natalieflp @vera-wes

**Comment by taylordowns2000** [comment]
Heyo @aleksagk !

The 3rd issue has been delivered. For the 2nd issue here, we currently display a green check for 0, a red X for 1, and a yellow triangle for anything above 1. Is there a different error code you're looking for?

For the first issue, this is a little more complex because some receipts are linked to more than one active job. It's still an important piece of functionality. Would it be OK to have it live on the runs list (activity history) instead of the receipts list (inbox)?

**Comment by vera-wes** [comment]
Hey @taylordowns2000, thanks for keeping us up to date here! 

Totally understand about the first issue - I think we'd tagged this in issue #80 otherwise, as exporting logs could offer us something kind of analogous. Best case scenario though, that still should skirt the issue you raised about being linked to more than one job, is to only expose the functionality after you've filtered by trigger. So you drill down to only those receipts that match X and then can only reprocess using job X, rather than any one of the jobs that matches that message. Does that make sense/feel feasible?

I think what would be most useful to us and our clients re:error code is language pack specific - being able to expose the logs outside the run log so that we can, for example, filter out all the duplicate errors and focus on external ID errors or filter out all the external ID errors so we can focus on troubleshooting records in the destination system that are missing a required field. So far the language pack we'd get most benefit from this functionality is SF, but I'm happy to talk more about what some intermediate level of information would be that is more than 0 , 1, >1 but not so specific to our use case.

**Comment by taylordowns2000** [comment]
Closing this as mass-reprocessing now lives on its own issue: #87
