### ISSUE TITLE
Activity tab - add "Needs manual processing" option to Filter Status dropdown

### ISSUE THREAD

**Issue by acawood777** [OpenFn/docs#57]
Currently only SUCCESS or FAILURE can be specified.
Submissions for Jobs that are set to OFF do not display here.

**Comment by taylordowns2000** [comment]
This is a good point and I'd love to push for a few more opinions here.

`Inbox` displays all of the messages received by OpenFn.
`Activity` displays all of the submissions sent to other systems by OpenFn.

As the system currently stands, we display a "mock submission" whenever a message matches the filter for a job but that job isn't running. You can view these mock submissions, and manually process them from the `Inbox` page, but I wanted to keep them off the `Activty` page because, strictly speaking, OpenFn didn't "do anything" and you're not being charged for a "job run" in these cases.

What are your thoughts on where this information (specifically, that a message has matched with a job, but no submission has been sent by OpenFn) should live in the system?

Thanks!

**Comment by acawood777** [comment]
**I'll start with our particular use case that sparked this request:**

- I set up a trigger on SalesForce that sends an SMS using Telerivet via OpenFn. THis is triggered with the insert of records into SF.
- The job was kept turned off for debugging.
- I initially submitted a few test records and could view them at the top of the `Inbox`.
- After that I wanted to test using real data submissions for a week or so before activating the job.
- The problem here is that we have enough data flowing on other jobs that these were far and few between - too sparse to view by paging through the `Inbox`, and I can't filter for them on the `Activity `page.

**To answer your question:**
I suppose it depends on what your definition of `Activity` is. As a user I didn't immediately assume that this was only for jobs that actually "did something" - I was just looking for my messages! :o) 

It is the obvious place to filter for specific messages, so it makes more sense to me to include messages from jobs that are turned "off" than to put them somewhere else.

While we're on this, I realised the same is true for messages that don't match one of the filters. They appear at the top of the `Inbox` but are not filterable on the `Activity` page.

**Comment by taylordowns2000** [comment]
@acawood777 , sorry to leave you hanging for so long here! I'm not sure I understand the very last point in your previous comment. Is this still an issue for you, and if so, could you elaborate or send a screenshot on this: "While we're on this, I realised the same is true for messages that don't match one of the filters. They appear at the top of the `Inbox` but are not filterable on the `Activity` page."

**Comment by acawood777** [comment]
@taylordowns2000 

**Summary:**
I would be happy with the functionality as it now is, but just change the text of "with no associated runs" to "with no active runs"

**Lengthier:**
The new inbox filter for "with no associated runs" solves both issues, thanks!
The only issue I have is with the wording...

Two clarify this (and my last point in the previous comment), there are 2 types of messages I was considering:
1) A message which doesn't match any job-filter
2) A message which matches a job-filter, but the job is currently turned OFF

At the moment "with no associated runs" filter in the inbox shows runs of both type (1) and (2) above:
![untitled](https://cloud.githubusercontent.com/assets/13887947/19930805/bda264b8-a112-11e6-90f8-01b437b07d89.png)

I would be happy to leave the functionality as it is, but just change the text of "with no associated runs" to "with no active runs"

Does that clarify things enough?

**Comment by taylordowns2000** [comment]
@acawood777 , that does clarify—thank you! I think that we've got to keep that text the way it is, because it is, quite literally, a filter that only shows messages with _no associated runs whatsoever_. A run is the execution of a job.

The last two columns in that table of messages show an aggregate of runs (History) and a list of jobs whose triggers match on the body of the message in question (Potential).

When you select "With no associated runs" you'll notice that you get a list of messages where the entire "History" column is blank.

Given all of this, I think what you're asking for is a way to filter on the "Potential" column, to show  messages that don't match any triggers for jobs. Is that correct?

Also, note that having a job turned ON or OFF only determines whether or not it will automatically run when a matching message arrives. It's got nothing to do with that Potential column, though you might infer (sometimes correctly) that a certain job is off if there is a match but no run history.

Will leave this open as, if I'm understanding correctly, it's a great feature request—filtering on potential rather than history. Will not be a straightforward implementation as that "does-it-match-anything-right-now?" calculation is done at the time of presentation, but good to get in the pipeline.

**Comment by taylordowns2000** [comment]
@acawood777 , @vera-wes, @carl-eis , I've added a filter to the Inbox that can be used in combination with the "associated runs" filter. You should now be able to select "with no associated runs" _while_ filtering to messages that match a specific trigger.
