### ISSUE TITLE
Successful Run Looks Incomplete

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/docs#68]
I have a few entries in my inbox that say "running" and have the blue dot next to them, but they are not still running, they were all successful. They also appear out of order in the list, with mine, for example, occurring on 8/27, and 8/31, but being listed among the runs that occurred today only. Please see the attached screenshots. 
<img width="1268" alt="screen shot 2016-09-09 at 7 39 27 pm" src="https://cloud.githubusercontent.com/assets/17291053/18407470/152e556a-76c6-11e6-860f-2a34bd6f6e85.png">
<img width="516" alt="screen shot 2016-09-09 at 7 41 15 pm" src="https://cloud.githubusercontent.com/assets/17291053/18407471/1a4cb438-76c6-11e6-8472-0b9efc3179c3.png">

**Comment by taylordowns2000** [comment]
Hi @Natalieflp , sorry for the delay here. There was, for a period of time, a bug with the "project nearing run limit" warning mailer. The error occurred several times over the last 7 days and was responsible for each instance of a run being left without an `exit_code` or `finished_at` value. We have fixed this issue, but it doesn't explain these much older runs. I'm still looking into those.

Right now @stuartc is enhancing the functionality that manages runs across the system and is aware of this issue. We'll likely be able to catch runs that aren't returning a proper exit_code when he's finished and I will keep you posted.

**Comment by taylordowns2000** [comment]
@Natalieflp , @aleksagk , since fixing the `nearing run limit` bug, I've been monitoring the system for any new occurrences of this issue and none have appeared. We've also just deployed @stuartc 's new run queuing and graceful restart functionality which eliminates a potential issue with very long running jobs getting cut off by system upgrades.

I'm marking this issue as closed but will continue to monitor it closely over the next few days.
