### ISSUE TITLE
difficult to understand where errors prevail in new UI

### ISSUE THREAD

**Issue by stephanielitus** [OpenFn/docs#72]
I'm having difficulty with two pages:
1.  On the Activity page, I hit the re-run icon from the list.  It was helpful that the "running" word then appeared at the top on the list so that I knew if that job was re-run successfully.  However, the corresponding old job (different message id) remains below with an error icon.  It's very difficult to review this list and understand what items still need attention.
2.  Instead of re-running a job from the Activity page, I tried clicking into the message id with an error icon.  On that message page, I clicked the Run Again button.  Unlike re-running from the Activity page, there is no "running" item listed at the top, which made me think that it didn't start.  Again, the old message id with an error icon is listed below even though the new run was successful.  I'd like to be able to ascertain which items are _still_ with an error, and not see the runs that have been resolved by re-running.

The green ribbon at the top with message alerts is not very helpful for me.  I can't tell if it's been updated with my most recent run or not.  Also, it says something like "Dismiss this to view 1 older alert.", however, there is no way to dismiss alerts.

**Comment by taylordowns2000** [comment]
Hi @stephanielitus , thanks for raising this! I think you're getting at a deep (and actually, non-technical) question of "the status of a message" vs. "the status of a run". Will break it up into three sections below:

## 1: "Activity" is a historical log of every `run`
The Activity tab shows a list of every `run`. Keeping that historical record of just what OpenFn has done is very important, and there's intentionally no way to delete or modify something in your Activity history. For runs that are linked to a specific message (a submission from CommCare, for your project) you can execute a new run _with the same `message` and `job`_ as an old run in the list. Clients "retry" runs like this after making a change to the `message` or editing some configuration in a destination system. Given your specific needs, I think that you should check out the "Inbox" tab, and filter to show only messages with "Jobs in a 'failed' state".

## 1.1: "Inbox" is a list of all `messages` received, with summary information on related runs
The Inbox tab shows a list of all of the `messages` received, with a column for associated activity ("History") and another for jobs with matching triggers that you can run by hand. Since many clients only care about the last run for a particular combination of a job and a message, we roll that information up to the Inbox page. If you've executed 10 runs with the same message and the same job, you'll see that the "final state" is equal to the outcome of the **last** run of those 10. In other words, if it failed 9 times, but then you changed something, ran it again, and it succeeded, you'd see the final state on the Inbox page show `success`.

## 2: "Message Inspector" is a detailed view of a message and all of its related activity
The message inspector is designed to show you which jobs _can_ be executed on a given message, and which runs _have_ taken for that message. In the attached image, I've just cliked the "run" button for a particular match, but the same thing can be done by clicking thre "run again" button from that list of historical runs. When I do so, I get an alert at the top of the screen notifying that the run has started, and I see the run appear in the list. When it's done, it is automatically updated without my having to refresh the screen. If you're following the same workflow, but that's not happening for you, it's possible that you've found a bug with the user interface.
![inspector](https://cloud.githubusercontent.com/assets/8732845/19682606/b51a2f0c-9aae-11e6-976f-2260740a8a6a.png)


## 3: The "Notifications" bar
Finally, to dismiss a notification—and view the others once you've got more than one—click the gray "x" on the right side of the notification panel. I've circled it in red here:
![dismiss](https://cloud.githubusercontent.com/assets/8732845/19681771/0c7e1988-9aab-11e6-8f65-4110bcd54719.png)

I hope that's helpful. Please let me know if you've got any questions.

**Comment by stephanielitus** [comment]
Hi Taylor,

Thank you for explaining the Inbox vs. Activity, that is very helpful - and
I'm kicking myself for not noticing or remembering that option!

For #2, I think there is a bug with the UI.  After clicking "Run Again" on
the individual run page, it redirects me back to the Activity list.
However, the run does not appear at the top with "running" and circle icon.

Steph

**Comment by taylordowns2000** [comment]
Hey Steph,

Because that `RunsList` is sorted by date, the run only appears at the top of the _first_ page on the Activity tab. If you've left that tab from the Nth page and get directed back after clicking "Run Again" it will keep you where you were... the Nth page rather than the first. I need to think about the proper flow for a moment—likely a redirect to the `RunView` of that new run you've just created, which we should hook up to WebSockets so it gets updated automatically when the run finishes.

Closing this issue now, but adding the new redirect flow to our internal roadmap! Thank you, @stephanielitus .

**Comment by Natalieflp** [comment]
I still think that it would be helpful to have a discussion about being able to tell if errors prevail or not. Because I use the Bridge with ODK, and there is the well documented issue that ODK sends duplicate submissions every once in a while, the filter on inbox "with jobs in a failed state" becomes ineffective to me because those particular submissions will always stay in a failed state. Could there ever be a way to: 1) Delete submissions, 2) manually mark a submission as excluded from a filter, successful, or to be ignored, or 3) create our own filters (e.g. jobs in a failed state that do not contain the word "duplicate")? 

Until then I rely on email filters to direct me only to the errors that are not duplicates, and make sure that I keep emails unread if I haven't reprocessed yet. 

I may be an edge case at this point, but I can certainly see how users in the future may have submissions that will always remain in the failed state, particularly ODK users, who won't be able to use the existing filter as it is now.

**Comment by taylordowns2000** [comment]
@Natalieflp , I think the most straightforward way to achieve this would be by deleting runs. We'll implement a trash system where deleted runs will remain in the trash for 30 days and will not show up on the runs list. After thirty days, they'll be deleted from the system.
