### ISSUE TITLE
Feature request: Allow sending failure notification e-mails to collaborators

### ISSUE THREAD

**Issue by acawood777** [OpenFn/docs#81]
Currently failure notifications can only be set under Account Settings for the whole org (all projects) to a single e-mail address, either to "Each Time" or "Never".

It would be useful to be able to set notifications per collaborator on the individual project Settings pages under UserAccess as well - a single check-box "Notify on failure". Ticking this box should override the global account setting.

**Comment by taylordowns2000** [comment]
Hey @acawood777 , the emails are controlled by user, rather than project or organization. So a collaborator can choose to subscribe to emails or not. I think that moving this down to the project level (so the field lives on the `UserProject` junction object would be good. It could then be controlled on the project settings page, and overridden by the user account settings—i.e., if I don't want emails from any project, i turn them off on my user account settings page. What do you think?

**Comment by acawood777** [comment]
@taylordowns2000 Sounds good - I agree with moving it to project level, with user settings override.

On the project settings, will you be able to indicate which collaborators to send mails to? Or will all collaborators receive notification by default?

**Comment by taylordowns2000** [comment]
We're shifting feature requests for the various products to the [forum](https://community.openfn.org/c/feature-requests/12) and will now use these docs issues for issues related to documentation only.

Migrated here: https://community.openfn.org/t/allow-sending-failure-notification-e-mails-to-collaborators/113
