### ISSUE TITLE
Can't seem to add users to a project space?

### ISSUE THREAD

**Issue by kzeigler** [OpenFn/docs#93]
I am attempting to add a collaborator to my project however, I get a red "/" circle sign over the add button when I try to click add. I know that the user has an account because they are part of another project space of mine. Any ideas?

**Comment by taylordowns2000** [comment]
You're likely blocked from adding a collaborator because the "Free" and "Solo" plans only allow a single user. "Startup" lets you have a team of 3 working on the project, and "Scale" lets you add unlimited users.

This is "bad UI" on our part—there needs to be a message displayed to the user. I'm converting it to an internal issue that we'll address in the next release and marking it as closed.
